### PR TITLE
Change tba_config default_year to 2020

### PR DESCRIPTION
**Pull request by ZachOrr**

### CODE REVIEW

**Comment by fangeugene** [comment]
This shouldn't matter we have the sitevar?

**Comment by ZachOrr** [comment]
Yes - I destroy my local setup frequently and this is driving me nuts 🙆‍♂

**Comment by fangeugene** [comment]
Just make it default to the current calendar year then?

**Comment by ZachOrr** [comment]
Mmm good deal. Can do!

**Pull request merged**
