### PR TITLE
Event table formatting

### PR DESCRIPTION
**Pull request by jaredhasenklein**
See #1842

### CODE REVIEW

**Comment by fangeugene** [comment]
Can  you fix the tabbing? Use spaces.

**Comment by jaredhasenklein** [comment]
Do you just mean the extra space?

**Comment by fangeugene** [comment]
No, the indentation is off. It should be aligned with `<br>`

**Comment by jaredhasenklein** [comment]
oops. yes fixed

**Comment by jaredhasenklein** [comment]
One more thought on this topic:

We may want to list event status other than the next match or alliance selection. It would be helpful to know if the event is complete (final matches played), if the event is offline, or if matches haven't started yet. I'm definitely not a good person to code that but maybe someone wants to

**Pull request merged**
