### PR TITLE
Subdivide trusted api permissions

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Removes EVENT_DATA permission and splits it up so each endpoint has its own permission. 

Split from #1197

### CODE REVIEW

**Comment by fangeugene** [comment]
is `EVENT_DATA` completely unused now? If so, we should remove it from auth_type.py and renumber everything. It's okay to remove and renumber because we currently don't have any Auths in the DB.

**Comment by fangeugene** [comment]
Also, can you make the tests test each of the auth types individually?

**Comment by phil-lopreiato** [comment]
I've removed `EVENT_DATA` and updated the tests. Anything else?

**Comment by gregmarra** [comment]
I think it's generally bad practice to renumber enums. The point is you shouldn't be thinking about the numbers, and we aren't constrained in total size.

**Comment by fangeugene** [comment]
Yeah, @gregmarra is right. Should we keep the original numbers but comment out the ones that are deprecated?

**Comment by phil-lopreiato** [comment]
That's probably a better approach. Let me revert that commit

**Comment by phil-lopreiato** [comment]
All right, that should be better

**Pull request merged**
