### PR TITLE
District inverf(x) fix

### PR DESCRIPTION
**Pull request by flyingcow93**
fix for the inverf(x) function

### CODE REVIEW

**Comment by gregmarra** [comment]
This would be a great opportunity to add tests :)

@fangeugene , who is best to review this pull req?

**Comment by fangeugene** [comment]
Hopefully I'll have time to review it tomorrow.

**Comment by fangeugene** [comment]
There are some issues with this (such as missing import) but I will fix it after merging.

**Comment by flyingcow93** [comment]
Out of curiosity, how long will it take for the change to take effect?

**Comment by fangeugene** [comment]
Its live, cache should clear within 24 hours. I might manually flush it
later today.

**Pull request merged**
