### PR TITLE
iOS Support in myTBA

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Things we need to support iOS and myTBA

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
This should be good to go, I believe this is all we need to do server-side

**Comment by ZachOrr** [comment]
Sorry to bump this - is there something else we need before a merge?

**Comment by phil-lopreiato** [comment]
Nope, this is it

**Comment by ZachOrr** [comment]
Thank you! 😊

**Pull request merged**
