### PR TITLE
Standardize test format

### PR DESCRIPTION
**Pull request by andrewda**
This makes the test format more standard (and fixes a bunch of styling inconsistencies). Tests methods use snake_case, while non-test methods use camelCase. Also, `setUp()` and `tearDown()` are moved to the top of the test class.

Let me know if there's anything you'd like me to add/change or if I missed anything!

### CODE REVIEW

**Comment by andrewda** [comment]
Tests passing so I'm un-WIPing this.

**Comment by andrewda** [comment]
That last commit is bound to break something with ~1000 additions and ~1000 deletions...

But it's so beautiful now 😄

**Comment by andrewda** [comment]
I've never been so happy that a test passed in my life. 😃

**Comment by phil-lopreiato** [comment]
Holy giant diff batman! Tests pass, so I guess it's good...

**Pull request merged**
