### PR TITLE
Embed video for highest scoring match if available

### PR DESCRIPTION
**Pull request by tsteward**
This embeds the video(s) for the highest scoring match on the insights page for each year if it is available as described in #383. Should I also do this to the insights on the landing page?

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
How does this look if there are multiple videos for a match? Can you share a screenshot?

**Comment by tsteward** [comment]
screen shot 2016-05-10 at 10 45 33 pm
screen shot 2016-05-10 at 10 45 37 pm
It takes up a lot of space with two videos. Maybe we could limit it to one. I am not sure how we would pick which video to show if we limited it to one.

**Comment by tsteward** [comment]
Maybe we could tile them horizontally if there are two. There is still a problem if there are three or more.
screen shot 2016-05-10 at 10 51 36 pm

**Comment by gregmarra** [comment]
I'd slice off the first one for now – this isn't a problem for 2016, so we
can punt – we'll probably redesign this screen again before it is :)

**Comment by tsteward** [comment]
I made it so that only the first video is shown.

When this is merged I think that the insights page for each year will need to be recalculated.

**Pull request merged**
