### PR TITLE
Add "OTHER" award type to award helper

### PR DESCRIPTION
**Pull request by FletcherS7**
## Description
Added OTHER award type to the award helper.

## Motivation and Context
Allow submitting other award type from Cheesy Arena

## How Has This Been Tested?
Simple change. 
not tested. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change API specifications or require data migrations)

### CODE REVIEW

**Comment by fangeugene** [comment]
This actually doesn't work. Awards of the same type will get merged into one award. If we want to do this, we need `OTHER1`, `OTHER2`, `OTHER3`... for as many "Other" awards we want to support.

**Comment by FletcherS7** [comment]
Would it not be fine if only one award was submitted as other per event?

**Comment by fangeugene** [comment]
Yes that would be fine.

**Comment by FletcherS7** [comment]
sounds good.
I might add a note to the cheesy award display.

**Pull request merged**
