### PR TITLE
Ignore matches without a score

### LINKED ISSUE #1223: Event Wizard - FMS Results input after Quarters returns frcundefined error
Attempting to import match results after Quarterfinals returns an frcundefined error due to Finals schedule being unknown.

Workaround: Manually delete Finals rows from the spreadsheet before importing.

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Fixes #1223

### CODE REVIEW

**Comment by dracco1993** [comment]
@SUPERCILEX Is @phil-lopreiato's comment still relevant?

> Actually, time shouldn't be a mandatory field here. Just check for 'Red Score' and 'Blue Score'

**Comment by SUPERCILEX** [comment]
@dracco1993 I ignored that because the code has been fine like that for over a year and I don't want to break stuff. @phil-lopreiato do you still want to move forward with that change?

**Comment by phil-lopreiato** [comment]
Ummm... I don't remember. I guess this depends on a few things...

 1. Can you reproduce the bug outlined in https://github.com/the-blue-alliance/the-blue-alliance/issues/1223? You can use the FMS report attached to test. Note that the case outlined is when a future competition level isn't fully determined, so there are missing team numbers and scores (so you'll have to remove parts of this report).
[NYSU2017_MatchResultsReport_Playoffs.xlsx](https://github.com/the-blue-alliance/the-blue-alliance/files/984927/NYSU2017_MatchResultsReport_Playoffs.xlsx)

  2. If the bug still exists, can you verify that this patch actually resolves them?

**Comment by SUPERCILEX** [comment]
@phil-lopreiato I have an AP test coming up, but yeah I'll make sure the bug is still around soon™.

**Comment by SUPERCILEX** [comment]
Google I/O just happened so I don't see myself having much time to play around with this. Dunno if you want to close the other one too?

**Pull request closed without merging**
