### PR TITLE
Favicon with updated logo

### PR DESCRIPTION
**Pull request by jaredhasenklein**
Converted the new logo to a favicon. It doesn't have a transparent background like the previous one because there isn't a great configuration that I thought of to have transparency and maintain the color scheme.

### CODE REVIEW

**Comment by fangeugene** [comment]
Can you try using the circular logo as well as just the lamp part (changed to blue with no background)? Also, adding screenshots would help.

**Comment by jaredhasenklein** [comment]
I played in AI on PS so here are three different versions with previews of the icon in different contexts (there is a third party app that does a great job of that part).

https://drive.google.com/drive/folders/0B7KVTj--N5d4SUJIb0ZFT0Z6bTA

**Comment by fangeugene** [comment]
That's awesome. I think I'm a fan of the circle. Do others have opinions?

**Comment by brandondean** [comment]
I'm a fan of the circle.

**Comment by nwalters512** [comment]
Yeah, the circle looks great!

**Comment by jaredhasenklein** [comment]
Circle has been uploaded to the PR

**Pull request merged**
