### PR TITLE
Update the home page and myTBA pages for iOS

### PR DESCRIPTION
**Pull request by ZachOrr**
I updated the index pages and myTBA pages to remove the Android-only language. I abstracted some of the duplicated text by using partials.

Along with updating the home page, I included a new Google Play icon that's much higher quality.

Hold off on merging until the iOS app goes live in the store so the App Store actually goes somewhere.

screen shot 2018-12-04 at 3 55 06 pm
screen shot 2018-12-04 at 4 21 26 pm
screen shot 2018-12-04 at 4 21 38 pm

### CODE REVIEW

**Comment by ZachOrr** [comment]
Added a smart app banner for this - screenshot using a different app, the code in this branch uses our app ID
img_0606

**Comment by fangeugene** [comment]
Going to merge this tonight if @ZachOrr or someone verifies that the install banner works correctly.

**Comment by bdaroz** [comment]
LGTM 👍

**Comment by ZachOrr** [comment]
I can also verify the banner works, once I’m at my home machine this evening

**Comment by ZachOrr** [comment]
The app store banner looks great 🙌  
img_0808

**Pull request merged**
