### PR TITLE
pavement: Reformat file

### PR DESCRIPTION
**Pull request by mc10**
This makes indentation 4 spaces and converts all strings to be double quoted.

### CODE REVIEW

**Comment by gregmarra** [comment]
Looks good to me. How did you test this, perhaps by running paver preflight?

**Comment by mc10** [comment]
Tbh I didn't really test this because I couldn't figure out how to set up Paver on my local machine.

**Comment by gregmarra** [comment]
Tested by running `paver preflight`, verifying same output as before.

**Comment by gregmarra** [comment]
@mc10 we should make the paver setup instructions better. What roadbumps did you hit?

**Comment by mc10** [comment]
Does `paver setup` need to be run before `paver preflight`? Also, I ran into a "no `jinja2` module" error, but I guess that can be fixed with a simple install.

**Comment by phil-lopreiato** [comment]
Yeah, we need to add `jinja2` into the readme so that it gets installed with other npm (I think? Or is it from pip?) dependencies.

**Comment by gregmarra** [comment]
I'm editing it now :)

**Pull request merged**
