### PR TITLE
Event Media Suggestions

### PR DESCRIPTION
**Pull request by phil-lopreiato**
screenshot from 2017-02-23 20-22-14

### CODE REVIEW

**Comment by fangeugene** [comment]
What does the suggestion page look like? What are our guidelines for what we will accept/reject?

**Comment by phil-lopreiato** [comment]
The suggestion page looks just like the one for suggesting team media. Here's the review page
screenshot from 2017-02-24 10-10-28

**Comment by fangeugene** [comment]
The suggestion page, not the review page.

**Comment by phil-lopreiato** [comment]
screenshot from 2017-02-24 10-11-59

**Comment by fangeugene** [comment]
Ah okay. I think we should be more clear about what we want media of, since I don't want it to just be a collection of everything people have taken. Unless we want to do that, in which case we need to change how we display things.

**Comment by phil-lopreiato** [comment]
Updated Screenshots:
screenshot from 2017-02-24 11-15-53
screenshot from 2017-02-24 11-16-06
screenshot from 2017-02-24 11-20-03

**Pull request merged**
