### PR TITLE
Build/deploy React Native bundle with web app

### PR DESCRIPTION
**Pull request by ZachOrr**
For https://github.com/the-blue-alliance/the-blue-alliance-ios/issues/138 - looking to build/host the React Native bundle used to supplement some views in the the iOS app on the web

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
I'm happy to merge this, but do you think that this is the right approach (as opposed to putting all the RN stuff in this repo)? This way, there's no guarantee that RN changes get deployed in a timely manor if there are no www commits.

**Comment by fangeugene** [comment]
Is a separate repo that deploys to something like firebase hosting sound like a better option?

**Comment by ZachOrr** [comment]
If we want to host on Firebase, we have this PR ready to merge which will deploy to Firebase when there's changes in the RN branch https://github.com/the-blue-alliance/the-blue-alliance-react/pull/7

@phil-lopreiato We pull the RN code in to the iOS repo so we can deploy a copy locally with the iOS app, so it shouldn't live in the web repo

**Comment by phil-lopreiato** [comment]
Woah hey, we should probably just merge that other PR...

**Comment by ZachOrr** [comment]
We will have to setup the service worker stuff, but also all of the RN service code in the iOS app interfaces with Firebase Storage so that's all set

Just waiting on a decision on this one - feel free to close this PR if we wanna go with the other PR

**Comment by phil-lopreiato** [comment]
I think the other PR is the right approach, although I think there's a bit of work on my end to set up the right keys for the prod instance

**Pull request closed without merging**
