### PR TITLE
Add instagram to team social media

### PR DESCRIPTION
**Pull request by tsteward**
This adds instagram support to team social media

Currently this just links to the instagram profile on the review page. Should I use a widget like [this](http://www.jqueryscript.net/social-media/jQuery-Plugin-To-Display-An-Instagram-Profile-Widget-On-The-Webpage.html) instead?

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Yeah, please use the widget in the review queue (it makes it so much easier on the review side). Can you add a screenshot of an item in review and how it renders on the team detail page as well?

Heads up, if https://github.com/the-blue-alliance/the-blue-alliance/pull/1527 (some simplification of the templates) gets merged before this, it'll conflict.

**Comment by fangeugene** [comment]
This needs rebasing.

**Comment by tsteward** [comment]
Rebased.

I am having difficulties getting the widget working.

Here are some screenshots:
capture
capture

**Comment by phil-lopreiato** [comment]
@tsteward I think this is good to go, good stuff! I don't think it's a huge deal about the widget, especially since it requires an API key. 

#shipit

**Comment by technonerdz** [comment]
This will be so cool!

**Comment by fangeugene** [comment]
Nice work.

Could you add an entry to https://github.com/the-blue-alliance/the-blue-alliance/blob/master/helpers/media_helper.py#L14 so that Instagram sorts before GitHub.

**Comment by tsteward** [comment]
This should be good to go.

**Comment by phil-lopreiato** [comment]
This should be live!
See http://www.thebluealliance.com/team/604

**Pull request merged**
