### PR TITLE
Add support for 9xxx teams

### PR DESCRIPTION
**Pull request by dracco1993**
## Description
Add support for 9xxx teams

## Motivation and Context
[Someone reported it](https://www.facebook.com/groups/moardata/posts/5713396142013967/), [`frc-events` has teams over 9k](https://frc-events.firstinspires.org/2023/allteams), and, you know, those teams deserve to be seen as well.  😂
I didn't _see_ anywhere else this would need to be changed, but can make whatever additional changes are needed, if any.

## How Has This Been Tested?
It worked locally.  👀 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change API specifications or require data migrations)

### CODE REVIEW

**Comment by fangeugene** [comment]
What's the max team number this year? I think first used to reserve 9900+ for off-season teams (do they still?). We should find a way to robustly support fake team numbers.

**Comment by dracco1993** [comment]
> What's the max team number this year? I think first used to reserve 9900+ for off-season teams (do they still?). We should find a way to robustly support fake team numbers.

According to `frc-events`, [9176 is now a legitimate team](https://frc-events.firstinspires.org/2023/allteams).  👀

**Comment by fangeugene** [comment]
Can we go to 9500 instead of 10000 so the fake teams stay hidden?

**Comment by dracco1993** [comment]
Looking into it more, changing it to `9500` seems like it wouldn't prohibit those 9900+ teams from being shown, as the value is only used to calculate the valid pages, not the range of teams to show.  We could certainly add an actual limit to the results, but that'll take a bit more code.

**Comment by fangeugene** [comment]
Ah you're right. Ok I think it's fine for now then

**Review by fangeugene — APPROVED** [review]

**Pull request merged**
