### PR TITLE
Permissions

### PR DESCRIPTION
**Pull request by gregmarra**
Commandeers #757 and makes a few changes to simplify things for an initial implementation of permissions.

My current plan is to leave the "admin panel" requiring appengine admin, and move other functions out into other paths that aren't the admin panel. This will allow a piecewise conversion of functionality.

### CODE REVIEW

**Comment by gregmarra** [comment]
Test failures are unrelated to these changes and need to be fixed separately.

**Comment by gregmarra** [comment]
@fangeugene @chrismarra can you review these?

**Comment by chrismarra** [comment]
Whoops, I thought someone had commandeered this after I left it hanging.
I'll get my dev environment set up on my work laptop and see if I can
verify this still works on an upcoming flight.

**Comment by chrismarra** [comment]
This looks alright to me so far, but I'm getting my SDK setup on my work laptop so I can run it.

**Comment by gregmarra** [comment]
Tests pass locally, going to merge this.

**Comment by fangeugene** [comment]
What's the purpose of this?

**Comment by gregmarra** [comment]
It will allow us to start enabling other people to admin certain aspects of the site without having full AppEngine admin permissions.

Look at #1273 as an example.

**Comment by fangeugene** [comment]
Ok that's great.

**Pull request merged**
