### PR TITLE
Subscription Firehose

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Add the UI for subscribing to all events within a year. Uses underlying keys like ```2015*```

### CODE REVIEW

**Comment by ZachOrr** [comment]
❤️

**Comment by fangeugene** [comment]
Not live yet, I'll let you know when it is =)

**Comment by fangeugene** [comment]
For those not on Twitter, it is live.

**Comment by first3234** [comment]
the subscription thing crashed and deleted all  of the events i had subscribed to

**Comment by phil-lopreiato** [comment]
Can you provide some more information? I can't reproduce this. 

Are you using the app? What version is it?

**Comment by first3234** [comment]
the app and the latest version

**Comment by phil-lopreiato** [comment]
What's the version number? Is there any more information you can provide?

Also, please move discussion on this to this issue: https://github.com/the-blue-alliance/the-blue-alliance-android/issues/310

**Comment by ZachOrr** [comment]
Will there eventually be more subscription options available than just match notifications?

**Comment by phil-lopreiato** [comment]
Yes. #1098 enables a [few more](https://github.com/the-blue-alliance/the-blue-alliance/pull/1098/files#diff-10ab16b882db2b7ebd73ca0a674b652dR75). And then I'll get around to doing the rest of them after that.

**Comment by ZachOrr** [comment]
Very cool! No rush. Match notifications are my only personal priority. Thanks! :)

**Pull request merged**
