### PR TITLE
Adds Facebook page plugin to homepage LHC.

### PR DESCRIPTION
**Pull request by gregmarra**
Will make it easier for people to Like our Facebook page, sets us up for doing something similar on team pages.

Plugin automatically gets narrower when needed (only on page reload, but not a problem for mobile devices).

screen shot 2015-04-19 at 17 09 00

### CODE REVIEW

**Comment by gregmarra** [comment]
@fangeugene can you give me a quick LGTM? :)

**Comment by fangeugene** [comment]
Looks good to me, but the slightest bit busy IMO. Thoughts, @gregmarra ?

**Comment by synth3tk** [comment]
Revisiting this, do we still want to do it?

**Comment by fangeugene** [comment]
I'm no a huge fan of how busy it is

**Comment by SUPERCILEX** [comment]
@fangeugene Do you want to close this? TBA now has an "Upcoming events" section which kinda takes care of this:
image

**Comment by synth3tk** [comment]
It doesn't cover all of the other posts types, but I'm not sure if that's even necessary at all. IMHO, we can go without the FB widget.

**Comment by andrewda** [comment]
I agree.

**Comment by fangeugene** [comment]
We can revisit making a "like" button on the homepage more prominent, but I think the widget is overkill.

**Pull request closed without merging**
