### PR TITLE
updated favicon logo AND size

### PR DESCRIPTION
**Pull request by jaredhasenklein**
It occurred to me that most browsers want a 32 by 32 favicon and not a 64 by 64

### CODE REVIEW

**Comment by jaredhasenklein** [comment]
See #1841 for updated logo thread

**Comment by fangeugene** [comment]
This is still 64x64?

**Comment by jaredhasenklein** [comment]
Github was doing some weird things ignoring the upload...I think the most recent version should be good.

**Comment by fangeugene** [comment]
Is the PNG supposed to be included? GitHub won't let me merge. Can you rebase with master? Thanks.

**Comment by jaredhasenklein** [comment]
I believe we need `<link rel="shortcut icon" href="/favicon.ico" />` and also `<link rel="icon" type="image/png" href="/favicon.png" />` once the files are uploaded.

I don't know my way around here yet to know exactly where that goes but I would suspect [here](https://github.com/the-blue-alliance/the-blue-alliance/blob/050e299e4e488f92c1e14fe3d4edcb663c40482e/subtrees/bootstrap/docs/_includes/header.html). If that's correct, I'll rebase with both files and the updated code. Can you confirm location?

**Comment by fangeugene** [comment]
It should go in 2 places:
https://github.com/the-blue-alliance/the-blue-alliance/blob/050e299e4e488f92c1e14fe3d4edcb663c40482e/templates/base.html
https://github.com/the-blue-alliance/the-blue-alliance/blob/050e299e4e488f92c1e14fe3d4edcb663c40482e/templates_jinja2/base.html

While you're doing this, maybe it's worth setting all of the different icons that iOS and Android expect as well?

**Comment by technonerdz** [comment]
I manage a bunch of website and I always use the same tool to generate fav icon files. To support everything, the code should look like that:
`<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">`

You can use this tool to generate this automatically : [http://www.favicon-generator.org](url)

I am willing to do it but I think @jaredhasenklein is on the right track so i'm just giving this information.

**Comment by jaredhasenklein** [comment]
Yeah thanks @technonerdz. I'm already on it. 

I'll open a new PR soon. @fangeugene Only thing I don't know is what directory the files should go in

**Comment by phil-lopreiato** [comment]
You should put them in the `static` directory (and likely make a new subdirectory). You'll have to update the mappings in `app.yaml` and you can use a wildcard to catch them all if you handle the naming properly.

See here for reference: https://cloud.google.com/appengine/docs/standard/python/getting-started/serving-static-files

**Comment by jaredhasenklein** [comment]
I'm afraid that even when looking at the link from @phil-lopreiato, this is beyond my capabilities. If someone wants to give me some more guidance, I can try and do it but it may just be easier for someone else to handle that part. I have icons ready and plan is to put them in `static/icons`

**Comment by jaredhasenklein** [comment]
Here are the icons and the code that is needed to get them going (code assumes directory is `static/icons`). Happy to keep going but not sure what to do about mapping.

[Source of icons listed as `static/icons`](https://github.com/the-blue-alliance/the-blue-alliance/files/859508/icons.zip)`

```
<link rel="apple-touch-icon" sizes="180x180" href="/static/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/static/icons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/static/icons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/static/icons/manifest.json">
<link rel="mask-icon" href="/static/icons/safari-pinned-tab.svg" color="#4d5fbc">
<link rel="shortcut icon" href="/static/icons/favicon.ico">
<meta name="msapplication-config" content="/static/icons/browserconfig.xml">
<meta name="theme-color" content="#4d5fbc">`

**Comment by phil-lopreiato** [comment]
You can do it! I'm happy to explain it for you.

By default, app engine won't directly serve a file from the repository. If you want that to happen, you have to specifically add a mapping into `app.yaml`. Think of is as a whitelist of files browsers are allowed to access.

You'll have to add a static handler for the `icons` directory. For example, here's the [handler for css files](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/app.yaml#L31). You'll want to add something like this (if you put all the images in `static/icons`):

```
- url: /icons
static_dir: static/icons
```

The `url` item is the user-visible location (what you'll put in the browser's address bar), and the `static_dir` points to the location in the file tree where those files actually live.

In this case, you'd want the `link` tags to look like:

```
<link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png">
```

which would link to the file found in `/static/icons/apple-touch-icon.png`

**Comment by jaredhasenklein** [comment]
I think I'm getting it... If I do
```
- url: /icons
static_dir: static/icons
```
like you said, will that automatically encompass everything within the directory? I noticed that currently in `app.yaml` there are individual files and not directories listed.

**Comment by phil-lopreiato** [comment]
Yes, it will take the whole directory. For example, the `css` and `javascript` handlers reference entire directories.

**Comment by jaredhasenklein** [comment]
Gotcha. I think this'll should do it. Standby

**Comment by jaredhasenklein** [comment]
Closing this and moving to #1852

**Pull request closed without merging**
