### PR TITLE
Remove a bunch of unused imports

### PR DESCRIPTION
**Pull request by legoktm**
Mostly detected using flake8.

### CODE REVIEW

**Comment by gregmarra** [comment]
Whoo! Is there a way we can automate this in paver?

**Comment by gregmarra** [comment]
This pull got stale. Want to update it and I'll merge?

**Comment by synth3tk** [comment]
This is wildly out-of-date. I'm thinking it's best to restart this PR, if it's still needed.

**Comment by fangeugene** [comment]
Agreed.

**Pull request closed without merging**
