### PR TITLE
[GD2] Design overhaul!

### PR DESCRIPTION
**Pull request by nwalters512**
Sorry in advance for the monolithic PR, this wasn't really something that could be done piecemeal.

This contains a rewrite of a good portion of GD2 using the lovely [Material UI](http://www.material-ui.com/#/) library for React. It should feel a lot better than the generic Bootstrap app we had before.

Other things that were convenient to do along the way:

* Moved away from CSS styles and towards inline styles. This helps us adhere to the React idea that components should be largely self-contained.
* Rewrote all components to be ES6 classes; used a few more ES6+ goodies throughout.
* Better handling of webcasts when switching between layouts. GD will now retain as many webcasts as possible when switching to a view with fewer available cells.
* A bunch of bug fixes
* A few updates to various dependencies.

Test away! I'd like some feedback before I merge.

Imgur
Imgur
Imgur

### CODE REVIEW

**Comment by nwalters512** [comment]
Updated screenshots showing the new layout icons. Also changed the subheaders in the layout drawer to use the primary color.

Imgur
Imgur

**Comment by nwalters512** [comment]
Just realized that the layout selection screen that's displayed when you visit GD with no URL params is broken because I removed Bootstrap (and its responsive grid) from the page. I'll have to fix that before this is merged.

**Comment by nwalters512** [comment]
That's better:

Imgur

**Comment by phil-lopreiato** [comment]
Check is out: http://tba.lopreiato.me/gameday2

**Comment by bdaroz** [comment]
Probably late to the game, but the match update sidebar? Gone or integrated w/ the social sidebar?

**Comment by nwalters512** [comment]
On the roadmap. In fact, we're probably getting rid of the Twitter feed entirely in favor of the live ticker. This PR is targeting mainly appearance, not functionality. I'll try to get feature parity with GD1 before competitions start!

**Pull request merged**
