### PR TITLE
Add team history robots apiv2 endpoint

### PR DESCRIPTION
**Pull request by phil-lopreiato**
Still needs query cache clearing

### CODE REVIEW

**Comment by patfair** [comment]
Will this get merged/deployed anytime soon? Need it for Chezy Champs.

**Comment by phil-lopreiato** [comment]
@fangeugene?

It's all good on my end - you said you'd take care of the query cache clearing for me (if you changed your mind, you'll have to tell me what to do :P)

**Comment by fangeugene** [comment]
Working on it.

**Comment by fangeugene** [comment]
@patfair It's live.

**Comment by patfair** [comment]
Thanks, seems to work.

There's some bad data, but I'm assuming it's coming in that way from FIRST. For example, 1678's robot name for 2015 is listed as "Beca" but that was their 2014 robot, and there are no robots showing up for 649, 971 and 1868 among others.

**Comment by phil-lopreiato** [comment]
@patfair if the team doesn't input a robot name into TIMS, then it won't show up in the API.

I just hit the endpoint myself for 1678, and it looks like their name is wrong upstream as well.
```
 ~  frc-api https://frc-api.usfirst.org/api/v1.0/teams/2015/\?teamNumber\=1678
{"teams":[{"teamNumber":1678,"nameFull":"UCD Chancellor's Office / snip","nameShort":"Citrus Circuits","city":"Davis","stateProv":"California","country":"USA","rookieYear":2005,"robotName":"Beca","districtCode":null}],"teamCountTotal":1,"teamCountPage":1,"pageCurrent":1,"pageTotal":1}
```

**Comment by fangeugene** [comment]
Looks like a standard case of bad FIRST data. I'm assuming 1678/971/1686/etc did actually name their robot this year and didn't screw up TIMS.

**Pull request merged**
