### PR TITLE
Hot matches

### PR DESCRIPTION
**Pull request by fangeugene**
image

### CODE REVIEW

**Comment by engunneer** [comment]
Feature request: Add a match time column to the top matches page. I want to subscribe to top matches today, but not tomorrow, or not get subscribed to matches during my big meeting later, etc.

**Comment by fangeugene** [comment]
@phil-lopreiato I won't be able to do this, but it's pretty simple to do by looking at the upcoming matches table and copying the appropriate header and row `<td>`

**Comment by phil-lopreiato** [comment]
Yeah, I'm going to spend some time this morning tweaking that page

**Comment by joelg236** [comment]
This is so great. At some point can there be a button to subscribe to all top 25 matches?

**Pull request merged**
