### PR TITLE
Temporarily remove CD from suggestions

### PR DESCRIPTION
**Pull request by jaredhasenklein**
Temporarily removes CD-media is a suggested media type

## Description

- Comments out the language suggesting it (so that we can easily add it back in when we start supporting again)
- Changes placeholder text on form to be an Imgur URL instead

## Motivation and Context
#2361 

## Next steps

- Fix 500 errors caused by submitting a previously-valid CD-media URL
- Start supporting photos from CD again

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change API specifications or require data migrations)

### CODE REVIEW

**Comment by fangeugene** [comment]
Can you reopen this PR but onto `master` instead of `py3`? thanks!

**Comment by ZachOrr** [comment]
@fangeugene It looks like you properly changed the base for this branch. We should be able to merge, yeah?

**Comment by fangeugene** [comment]
No, changing the base doesn't work, since the commit is branched from py3

**Comment by ZachOrr** [comment]
Oh lame. Sorry - I got it backwards zz

**Review by fangeugene — APPROVED** [review]

**Pull request merged**
