### PR TITLE
Add timeseries chart on match page

### PR DESCRIPTION
**Pull request by fangeugene**
## Description
Add timeseries chart on match page.
Add timeseries chart on dedicated page.  A lot of copypasta because no time to clean up right now.

## Motivation and Context
GDCV everything!

## How Has This Been Tested?
Local dev

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change API specifications or require data migrations)

### CODE REVIEW

**Comment by gregmarra** [comment]
Screenshot!

**Comment by fangeugene** [comment]
@gregmarra there is already one?

**Comment by gregmarra** [comment]
Oh not in the emails.

**Comment by gregmarra** [comment]
Oh actually it was just slow to load.

**Comment by fangeugene** [comment]
Does this chart make sense at all? The negative numbers for Blue may be confusing, but I'm not sure how else to show it.

**Pull request merged**
