### PR TITLE
Add warning for people using IE<10

### PR DESCRIPTION
**Pull request by nwalters512**
Jumping through hoops to support ~5% of our users doesn't make sense. This prompts everyone running IE <10 to update to a more modern browser.

Imgur

### CODE REVIEW

**Comment by fangeugene** [comment]
What is this "screenshot"

**Comment by nwalters512** [comment]
It's the warning shown to people using old versions of IE.

**Comment by fangeugene** [comment]
I mean did you take it with a phone or something?

**Comment by nwalters512** [comment]
Oh, yeah.

**Comment by fangeugene** [comment]
Now might be a good time to update do_compress.py to do a combined style for gameday2, and remove the changes to app.yaml.

**Comment by nwalters512** [comment]
... that was not the commit history I was expecting.

**Comment by fangeugene** [comment]
Lol wut

**Comment by nwalters512** [comment]
A rebase went wrong, I think that fixed it though.

**Comment by SUPERCILEX** [comment]
@fangeugene do we really care about IE?

**Comment by synth3tk** [comment]
If my Google Analytics-fu is correct, then during the 2017 season (Jan 7 - Apr 29), IE 9 and lower accounted for 3.31% of site-wide traffic and roughly less than 2% of GameDay views.

The GameDay stat is based on 7.67% of sessions, due to some thing GA does that I honestly don't fully understand. But even being generous with the numbers, I can't imagine we're even close to 5% anymore.

**Comment by bdaroz** [comment]
At this point if anyone is using IE < 10 would one more warning really matter?

**Comment by fangeugene** [comment]
GA generates results based on a fraction of data if there are too many samples, but I got it to use 100% of the data.
from Jan 1 to April 30: 3.29% of sessions were IE, and <1.5% of that were IE<10.

**Comment by synth3tk** [comment]
IMHO, no. If you're still using IE < 10 at this point, you'd have to know it breaks a lot of sites, and you probably see warnings on a daily basis elsewhere.

**Comment by fangeugene** [comment]
I'm fine with not having this.

**Comment by synth3tk** [comment]
Gotcha. Thanks, Eugene. Is there some magical way to pull that up?

**Comment by fangeugene** [comment]
@synth3tk Any "default" statistic should be using 100% of the data. Custom filters may limit what gets returned (e.g. if you filter by X-TBA-App-ID when looking at API requests)

**Comment by synth3tk** [comment]
That's probably what got me then. I did a custom report to show only /gameday with an IE browser.

**Pull request closed without merging**
