### PR TITLE
Datafeed rework

### PR DESCRIPTION
**Pull request by fangeugene**
Remove all unused datafeeds, add FIRSTElasticSearch datafeed.

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
So much simpler! :+1:

**Comment by gregmarra** [comment]
Does this completely remove the FMS API datafeeds? Do we anticipate wanting to use them (official) over the ES queries (unofficial)?

**Comment by fangeugene** [comment]
It keeps the FMS API and ES queries.
It removes the HTML datafeeds. We were only using 3 out of the dozen or so anyways, since they already got migrated to the FMS API.

**Comment by gregmarra** [comment]
Love it.

**Pull request merged**
