### PR TITLE
Updated to new FIRST logo. Fixes #1307

### LINKED ISSUE #1307: Update /images/first_logo.png to new logo

### PR DESCRIPTION
**Pull request by csteward24**
Note: The new image is a little shorter than the old one by about 32 pixels
By the way, am I supposed to reference the issue number in my commit? Because if so it's #1307

### CODE REVIEW

**Comment by fangeugene** [comment]
In the future if you want to put the note in the commit, it's best to put it on a new line in the commit message so it shows up as more info instead of part of the title. You can put "Fixes #1307" either in the commit or in the pull request title, and once this PR gets merged the issue will auto close. Can you edit the PR title to include "Fixes #1307"? Editing the commit message is more of a headache.

Thanks!

**Comment by fangeugene** [comment]
/about now has a distorted logo. You'll want to update the dimensions in `tba_about.less`

image

**Comment by csteward24** [comment]
Thank you for your guidance. I was looking for the CSS, totally forgot we
were using less. Will fix tommorow.
Il 11/mar/2016 00:19, "Eugene Fang" <notifications@github.com> ha scritto:

**Comment by fangeugene** [comment]
:+1:

**Pull request merged**
