### PR TITLE
Live Events API

### PR DESCRIPTION
**Pull request by phil-lopreiato**
API Endpoint for getting the live events at a specific time.

Parameter is UTC timestamp (will be normalized to last Monday) - this allows for deterministic cache keys. I do need some help with cache-busting, though. I'm not sure how to clear them, though - the clearer is passed a list of keys. Is there a way to translate those to the start times without database queries (which I assume shouldn't be done there)?

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
I think I've got the cache clearing all done here. Any further issues?

**Comment by phil-lopreiato** [comment]
I don't think the last failing test is my fault? How can I check if it is?

**Comment by popnbrown** [comment]
I think it may be your commit. I think your last 3 commits failed. https://travis-ci.org/the-blue-alliance/the-blue-alliance/pull_requests

https://travis-ci.org/the-blue-alliance/the-blue-alliance/builds/55892634
test_alliance_selections_update (test_api_trusted.TestApiTrustedController) ... FAIL
test_rankings_update (test_api_trusted.TestApiTrustedController) ... FAIL

You should be able to run the full testing suite on your local. I ran the fast version before.

**Comment by phil-lopreiato** [comment]
Yeah, I know that. But I didn't touch anything related to the trusted API. I'll have to dig into it further

**Comment by phil-lopreiato** [comment]
All better :)

**Comment by bdaroz** [comment]
Do we want to revisit this for APIv3 in #1507 or let this pass?

**Comment by fangeugene** [comment]
Closing this because APIv2 is getting deprecated.

**Pull request closed without merging**
