### PR TITLE
Count WFFA's won after 2015 as blue banners for insights

### PR DESCRIPTION
**Pull request by legoktm**
See <http://www.usfirst.org/roboticsprograms/frc/blog-honoring-woodie-flowers-finalist-award-winners>.

### CODE REVIEW

**Comment by fangeugene** [comment]
Dang, 604 should have 4 more banners then.

**Comment by fangeugene** [comment]
I'm kind of with Tom on this one.

**Comment by popnbrown** [comment]
While that's true, they (FIRST) wants to make the WFFA a team award as well. I mean by technical definition of having blue banners, the teams now have blue banners.

**Comment by synth3tk** [comment]
It seems like a grey area. Technically, the team now *displays* a blue banner that the individual won. But OTOH, the individual won it, not the team.

I'm leaning towards not counting it.

**Pull request closed without merging**
