### PR TITLE
Add website helper

### LINKED ISSUE #1949: Event websites missing scheme do not link correctly
For example, the website on the [BunnyBots event page](https://www.thebluealliance.com/event/2017orbb) (`team1540.org/competition`) is missing a `http://` or `https://`, so when clicked it links to `https://www.thebluealliance.com/event/team1540.org/competition` instead of the actual website.

### PR DESCRIPTION
**Pull request by andrewda**
This should fix #1949 (for future cases). Haven't had a chance to fully test locally, but I'll get a chance in a couple hours.

### CODE REVIEW

**Comment by andrewda** [comment]
Alright, this should be good to go. It won't fix links that are currently broken, though, those will probably have to be fixed manually.

**Comment by phil-lopreiato** [comment]
Can you update the [team info datafeed parser](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/datafeeds/parsers/fms_api/fms_api_team_details_parser.py#L35) to use this helper as well? We've had similar issues in the past with team websites, as well (see #1339 and #1635)

**Comment by andrewda** [comment]
Yup! Completely missed that, will update when I get home :)

**Comment by phil-lopreiato** [comment]
Oh - one more place. In the class `AdminEventEdit`, we should also sanitize the admin website input

**Comment by andrewda** [comment]
Apologies for not getting to this tonight — I've been training a neural network on my computer which has rendered it way too slow to do anything. Should be done by mid-tomorrow 😛

**Comment by andrewda** [comment]
Alright @phil-lopreiato should be good to go now!

**Pull request merged**
