### PR TITLE
The blue alliance messenger chatbot framework

### PR DESCRIPTION
**Pull request by technonerdz**
This is a framework for an eventual Facebook Messenger Chatbot for TBA as discussed with Greg. *Do not merge this* we need to add things to it before.

### CODE REVIEW

**Comment by technonerdz** [comment]
Do not merge this right now! We need to add things before.

**Comment by technonerdz** [comment]
Just realized that TBA does not have php hosting. Well... We will have to find another solution.

**Comment by phil-lopreiato** [comment]
Can you explain a little bit what the end vision of messenger bots for TBA is (what functionality will it provide)?

Additionally, TBA is all in python, which can also process the messenger webhooks. Look in `*-main.py` files to see url handlers and which controllers they map to.

**Comment by technonerdz** [comment]
A messenger bot to interact with the users on facebook. We could ask questions like: what is the status for a specific team, what is the next match for a team, informations about a team or an event like the website url or the next event date, the rankings for an event and much more.

**Comment by phil-lopreiato** [comment]
Have you taken a look at the [nightbot controller](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/controllers/nightbot_controller.py), which handles those kinds of queries for the gameday twitch chat?

**Comment by technonerdz** [comment]
Yup! That's a great idea to copy this code and modify it for messenger. I will check that later.

**Comment by technonerdz** [comment]
I am looking at the nightbot controller and it only show me how bad I am with Python.

**Comment by technonerdz** [comment]
I got how it works with nightbot! But Messenger is really different than nightbot. We have to send webhooks to the facebook API with an Key and all of those stuff. If someone knows pyhon more than me and want to help, you are welcome!

**Pull request closed without merging**
