### PR TITLE
Add EventInsights2018

### PR DESCRIPTION
**Pull request by ZachOrr**
Adds a model for `EventInsights2018`, as well as adding documentation for `unicorn_matches` to `EventInsights2017` - depends on #2269

## Motivation and Context

Just documenting things that haven't been documented

## How Has This Been Tested?

Looks good in Swagger editor

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change API specifications or require data migrations)

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Mind rebasing this on master?

**Comment by ZachOrr** [comment]
Yep standby

**Comment by ZachOrr** [comment]
Hang on I'm an idiot

**Comment by ZachOrr** [comment]
Okay cool, good to go 👍

**Comment by fletch3555** [comment]
This change likely should have bumped the Swagger spec version number.  Also, it's now invalid JSON (extraneous trailing comma: https://github.com/the-blue-alliance/the-blue-alliance/commit/c8c35603576a9c1e70aff25e567bfdc474bddc59?diff=split#diff-7766935448da0f93d95c066a1cae2bd0R4102), which is breaking consumers of the spec.  PR incoming

**Pull request merged**
