### PR TITLE
Server-Side Team@Event Status

### LINKED ISSUE #1628: Calculate Full Team@Event Status Serverside
As we use this more and more around the site, we should not be calculating this data both server-side and in the app. Some examples for testing can be found on [this fb thread](https://www.facebook.com/groups/moardata/permalink/1206221399398153/)

Here's what I'm thinking the json result should look like:

```
{
  'rank': {
    'rank': 1,
    'total': 60,
    'played': 12,
    'first_sort': 102 (first order sort item)
    'record': "12-0-0",
    'breakdown': string of all the ranking data for this team, like what shows in the app now
  },
  'alliance': {
    'position': one of {captain, 1st, 2nd, 3rd, backup},
    'name': name of alliance ("Alliance #1" or "Newton"),
    'backup': "backup" dict from alliance row
  },
  'playoff': {
    'status': one of {playing, eliminated, won (the event)},
    'round': one of {ef, qf, sf, f},
    'record': record in the playoffs
    'current_level_record': the team's record in the most recent playoff level (only if status is playing)
  }
}
```

### PR DESCRIPTION
**Pull request by phil-lopreiato**
This PR handles a full calculation of team@event statues serverside (as discussed in #1628).

A few notes:
 - Adds a new dependency for running tests, do `pip install appengine-fixture-loader`. This library is super cool, and makes setting up a datastore for a test much simpler
 - Qual data relies on the rankings, which has a record for every year except 2010. I wanted to avoid traversing the full list of matches for the event because it would be slow, and I figured this was an okay first implementation. We can come back and add that traversal in for 2010/offseason events later.
 - If a team is replaced by a backup (same for a backup team coming in), their playoff status reflects that of their alliance, not the matches in which that team participated, which is consistent with how awards are handled in these scenarios. This feature relies on the backup team implementation from #1520 (we may have to write a job to back-fill this data to past years)

Still TODO in future pulls:
 - Write tests for the status strings generated from this data (used by nightbot)
 - Break that string generation out into a separate file for cleanliness
 - Other, more global db query optimizations
 - Convert other places calculating this stuff manually to these calls (e.g. data on team history pages)

Will resolve #1628

### CODE REVIEW

**Comment by phil-lopreiato** [comment]
Okay, I think this is good to go. Here are some sample results (from 2016nytr)

Event Winner/First Seed:
```
{
  "rank": {
    "first_sort": 39.0,
    "breakdown": "Ranking Score: 39.0, Auto: 310.0, Scale/Challenge: 165.0, Goals: 448.0, Defense: 600.0, Record (W-L-T): 11-1-0, Played: 12",
    "record": "11-1-0",
    "played": 12,
    "rank": 1,
    "total": 36
  },
  "playoff": {
    "level": "f",
    "record": "6-1",
    "status": "won"
  },
  "alliance": {
    "name": "Alliance 1",
    "backup": null,
    "position": 0
  }
}
```

Another team that got eliminated in the playoffs:
```
{
  "rank": {
    "first_sort": 28.0,
    "breakdown": "Ranking Score: 28.0, Auto: 260.0, Scale/Challenge: 150.0, Goals: 191.0, Defense: 575.0, Record (W-L-T): 9-3-0, Played: 12",
    "record": "9-3-0",
    "played": 12,
    "rank": 6,
    "total": 36
  },
  "playoff": {
    "level": "sf",
    "record": "2-3",
    "status": "eliminated"
  },
  "alliance": {
    "name": "Alliance 4",
    "backup": null,
    "position": 1
  }
}
```

Backup team coming in:
```
{
  "rank": {
    "first_sort": 20.0,
    "breakdown": "Ranking Score: 20.0, Auto: 192.0, Scale/Challenge: 105.0, Goals: 146.0, Defense: 525.0, Record (W-L-T): 6-6-0, Played: 12",
    "record": "6-6-0",
    "played": 12,
    "rank": 18,
    "total": 36
  },
  "playoff": {
    "level": "f",
    "record": "5-3",
    "status": "eliminated"
  },
  "alliance": {
    "name": "Alliance 2",
    "backup": {
      "out": "frc229",
      "in": "frc1665"
    },
    "position": -1
  }
}
```

Backup team coming out:
```
{
  "rank": {
    "first_sort": 20.0,
    "breakdown": "Ranking Score: 20.0, Auto: 156.0, Scale/Challenge: 130.0, Goals: 119.0, Defense: 525.0, Record (W-L-T): 6-6-0, Played: 12",
    "record": "6-6-0",
    "played": 12,
    "rank": 20,
    "total": 36
  },
  "playoff": {
    "level": "f",
    "record": "5-3",
    "status": "eliminated"
  },
  "alliance": {
    "name": "Alliance 2",
    "backup": {
      "out": "frc229",
      "in": "frc1665"
    },
    "position": 2
  }
}
```

A team not making playoffs:
```
{
  "rank": {
    "rank": 23,
    "played": 12,
    "breakdown": "Ranking Score: 19.0, Auto: 218.0, Scale/Challenge: 110.0, Goals: 159.0, Defense: 520.0, Record (W-L-T): 6-6-0, Played: 12",
    "first_sort": 19.0,
    "total": 36,
    "record": "6-6-0"
  },
  "alliance": null,
  "playoff": null
}
```

**Comment by bdaroz** [comment]
This looks great!

My only thought is a bit of future-proofing -- Can we use the W-L-T format for elim record as well and not just W-L?

Two reasons:
* First, it allows API users to use one common `convertWLT()` function in both places w/o having to do the regexp work to check for a tie value
* Second, and hopefully, _FIRST_ may turn around and allow some ties during elimination matches to trigger an extra match. If we calculate and present those values now, this is a piece of code that won't need an update for 2017 (or whenever).

**Comment by phil-lopreiato** [comment]
Good call, @bdaroz

**Comment by ZachOrr** [comment]
Is this exposed via the API?

**Comment by fangeugene** [comment]
"apiv3, coming soon"

**Pull request merged**
